import turtle
turtle.Screen().bgcolor("black") 
turtle.color('white')
turtle.speed(15)


def rectangle(x, y):
    turtle.setheading(0)
    for _ in range(2):
        turtle.forward(x)
        turtle.left(90)
        turtle.forward(y)
        turtle.left(90)

def paralelepipedo(x, y, front='#FF00E6', back='#00FFE0', ground='#FF0000', roof='#00FF0A'):
    turtle.setheading(0)
    turtle.color(ground)
    turtle.left(45)
    turtle.forward(x)
    turtle.left(45)
    turtle.color(back)
    turtle.forward(y)
    turtle.setheading(225)
    turtle.color(roof)
    turtle.forward(x)
    turtle.setheading(270)
    turtle.color(front)
    turtle.forward(y)

def make_house(largura, altura, comprimento, x, y, z):
    front = '#FF00E6'
    back = '#00FFE0'
    ground = '#FF0000'
    roof = '#00FF0A'
    cube_size = 20
    turtle.up()
    turtle.setpos(-(largura/2)-(comprimento/3), -(altura/2)-(comprimento/3))
    turtle.down()
    turtle.pensize(3)
    initial = turtle.pos()

    turtle.up()
    turtle.color('white')
    turtle.setheading(225)
    turtle.forward(80)
    turtle.down()
    turtle.setheading(0)
    turtle.forward(50)
    turtle.write('X', False, 'center', ('ISOCPEUR', 10))
    turtle.back(50)
    turtle.setheading(90)
    turtle.forward(50)
    turtle.write('Z', False, 'center', ('ISOCPEUR', 10))
    turtle.back(50)
    turtle.setheading(45)
    turtle.forward(50)
    turtle.write('Y', False, 'center', ('ISOCPEUR', 10))

    turtle.up()
    turtle.setpos(initial)
    turtle.down()
    turtle.color(ground)
    turtle.setheading(45)
    turtle.forward(comprimento)
    turtle.setheading(0)
    turtle.forward(largura)
    turtle.setheading(225)
    turtle.forward(comprimento)
    turtle.setheading(180)
    turtle.forward(largura)
    
    paralelepipedo(comprimento, altura)

    turtle.setheading(45)
    turtle.up()
    turtle.forward(comprimento)
    turtle.color(back)
    turtle.down()
    rectangle(largura, altura)

    turtle.up()
    turtle.setpos(initial)
    turtle.setheading(0)
    turtle.forward(x)
    turtle.setheading(45)
    turtle.forward(y)
    turtle.setheading(90)
    turtle.forward(z)
    ambiente_center = turtle.pos()
    turtle.color('white')
    turtle.setheading(270)
    turtle.forward(cube_size/2)
    turtle.setheading(180)
    turtle.forward(cube_size/2)
    turtle.setheading(225)
    turtle.forward(cube_size/2)
    turtle.down()
    rectangle(cube_size, cube_size)
    turtle.setheading(45)
    turtle.forward(cube_size)
    rectangle(cube_size, cube_size)
    turtle.setheading(90)
    turtle.forward(cube_size)
    turtle.setheading(225)
    turtle.forward(cube_size)
    turtle.back(cube_size)
    turtle.setheading(0)
    turtle.forward(cube_size)
    turtle.setheading(225)
    turtle.forward(cube_size)
    turtle.setheading(270)
    turtle.forward(cube_size)
    turtle.setheading(45)
    turtle.forward(cube_size)
    turtle.up()
    turtle.setpos(ambiente_center)
    turtle.pensize(1)
    turtle.down()
    turtle.setheading(225)
    turtle.forward(y)
    turtle.stamp()
    turtle.back(comprimento)
    turtle.up()
    turtle.setpos(ambiente_center)
    turtle.down()
    turtle.setheading(180)
    turtle.forward(x)
    turtle.back(largura)
    turtle.up()
    turtle.setpos(ambiente_center)
    turtle.down()
    turtle.setheading(270)
    turtle.forward(z)
    turtle.back(altura)
    turtle.pensize(3)

    turtle.up()
    turtle.setpos(initial)
    turtle.setheading(0)
    turtle.forward(largura)
    turtle.down()
    paralelepipedo(comprimento, altura)

    turtle.up()
    turtle.setpos(initial)
    turtle.down()
    turtle.color(front)
    rectangle(largura, altura)

    turtle.hideturtle()



make_house(largura=300,altura=150,comprimento=500,x=150,y=250,z=75)
turtle.mainloop()